typography_spectrum: 0.14933358831331134
color:
  brandColors:
    - '#D8CAA8'
    - '#5C832F'
    - '#284907'
    - '#382513'
    - '#363942'
  brandStrength: 0.4888945750426501
  lightness: 0.7566613527014852
  saturation: 0.585067642852664
  rhythmicContrast: 0.704560613958165
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.7416557495016605
analytics:
  google: null
  facebook: null
  twitter: null
name: Gravestone Imaging
cta:
  domain: null
  bucket: null
  version: null
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/40322356-97c0-417b-9744-2076b83e24f0.ico
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: ''
purpose: []
