color:
  brandStrength: 0
  saturation: 1
  brandColors:
    - '#a7c2df'
    - '#628145'
    - '#284310'
    - '#568bc1'
    - '#031000'
  lightness: 0.5
  rhythmicContrast: 0
title: Gravestone Imaging
analytics:
  facebook: null
  google: null
  twitter: null
collections:
  - index:
      paginate: true
      path: /
      number: 15
      navigable: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
cta:
  domain: null
  version: null
  bucket: null
favicon: null
layout_spectrum: 0.1798246
purpose: []
name: Gravestone Imaging
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.6638244
