name: Gravestone Imaging
favicon: null
layout_spectrum: 0.13594
typography_spectrum: 0.6638244
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#a7c2df'
    - '#628145'
    - '#284310'
    - '#568bc1'
    - '#031000'
  brandStrength: 0.02608327
  lightness: 0
  saturation: 0.01206252
  rhythmicContrast: 0.03762222
purpose: []
