layout_spectrum: 0.1697995
typography_spectrum: 0.6638244
color:
  lightness: 0.8363174
  brandStrength: 0.02608327
  saturation: 0.01206252
  rhythmicContrast: 0.03762222
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
name: Gravestone Imaging
