name: Gravestone Imaging
favicon: null
layout_spectrum: 0.1697995
typography_spectrum: 0.6638244
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#060606'
    - '#bebcb0'
    - '#727176'
    - '#464e59'
    - '#8d542c'
  brandStrength: 0.02608327
  lightness: 0.8363174
  saturation: 0.01206252
  rhythmicContrast: 0.03762222
purpose: []
