typography_spectrum: 0.832187172723934
color:
  brandStrength: 0.5354936299845576
  saturation: 0.8773064059205353
  brandColors:
    - '#D8CAA8'
    - '#5C832F'
    - '#284907'
    - '#382513'
    - '#363942'
  lightness: 0.1486889561638236
  rhythmicContrast: 0.8334109554998577
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.2988722
analytics:
  facebook: null
  google: null
  twitter: null
name: Gravestone Imaging
cta:
  domain: null
  bucket: null
  version: null
favicon: null
collections:
  - index:
      paginate: true
      path: /
      number: 15
      navigable: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
title: ''
purpose: []
