name: Gravestone Imaging
favicon: null
layout_spectrum: 1
typography_spectrum: 0.6638244
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#a7c2df'
    - '#628145'
    - '#284310'
    - '#568bc1'
    - '#031000'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
